ENV: development
APP:
  PORT: 8080
REDIS:
  HOST: localhost
  PORT: 6379
  DB: 0
SQLALCHEMY:
  DATABASE_URI: "mysql+pymysql://root:pdBGKGjRyX3Jb2Hn@localhost:3306/flask-starter-mysql?charset=utf8"
  SQLALCHEMY_ECHO: False